//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace ConsoleClient.VelibServiceReference
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "VelibServiceReference.IVelibService", CallbackContract = typeof(ConsoleClient.VelibServiceReference.IVelibServiceCallback))]
    public interface IVelibService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibService/SubscribeVelibAvailable", ReplyAction = "http://tempuri.org/IVelibService/SubscribeVelibAvailableResponse")]
        void SubscribeVelibAvailable(string city, string station);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IVelibService/SubscribeVelibAvailable", ReplyAction = "http://tempuri.org/IVelibService/SubscribeVelibAvailableResponse")]
        System.Threading.Tasks.Task SubscribeVelibAvailableAsync(string city, string station);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceCallback
    {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://tempuri.org/IVelibService/VelibAvailable")]
        void VelibAvailable(string station, string velibDispos);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVelibServiceChannel : ConsoleClient.VelibServiceReference.IVelibService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VelibServiceClient : System.ServiceModel.DuplexClientBase<ConsoleClient.VelibServiceReference.IVelibService>, ConsoleClient.VelibServiceReference.IVelibService
    {

        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance) :
                base(callbackInstance)
        {
        }

        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) :
                base(callbackInstance, endpointConfigurationName)
        {
        }

        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) :
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(callbackInstance, endpointConfigurationName, remoteAddress)
        {
        }

        public VelibServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(callbackInstance, binding, remoteAddress)
        {
        }

        public void SubscribeVelibAvailable(string city, string station)
        {
            base.Channel.SubscribeVelibAvailable(city, station);
        }

        public System.Threading.Tasks.Task SubscribeVelibAvailableAsync(string city, string station)
        {
            return base.Channel.SubscribeVelibAvailableAsync(city, station);
        }
    }

}